repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jenkins
    url: https://charts.jenkins.io
  - name: longhorn
    url: https://charts.longhorn.io

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.14.1
    values:
      - values/ingress-nginx/values.yaml

  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    version: 1.11.0
    values:
      - values/longhorn/values.yaml

  - name: jenkins
    namespace: jenkins
    createNamespace: true
    chart: jenkins/jenkins
    version: 5.8.122
    values:
      - values/jenkins/values.yaml

  - name: harbor
    namespace: harbor
    createNamespace: true
    chart: harbor/harbor
    version: 1.18.2
    values:
      - values/harbor/values.yaml